In [25]:
import numpy as np
import pandas as pd

In [26]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [27]:
import pandas as pd

df = pd.DataFrame({
    "soil_moisture": [
        0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
        0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30
    ],
    "temperature_c": [
        34, 30, 26, 22, 28, 30, 19, 22,
        35, 24, 33, 33, 21, 25, 20, 29
    ],
    "sunlight_hours": [
        9, 8, 7, 4, 8, 10, 3, 10,
        12, 5, 9, 11, 2, 6, 1, 9
    ],
    "needs_water": [
        1, 1, 1, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 1
    ]
})

In [28]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [29]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [30]:
X=df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
Y=df['needs_water']

In [31]:
X_MIN=X.min()
X_MAX=X.max()
X_Scaled=(X-X_MIN)/(X_MAX-X_MIN+1e-8)

In [32]:
X_Scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train, X_test, y_train, y_test = train_test_split( X_Scaled, Y, test_size=0.25, random_state=42,stratify=Y)

In [35]:
import torch.nn as nn

class Net(nn.Module):
    def __init__(self,input_dim):
        super().__init__()

        self.network=nn.Sequential(
            nn.Linear(input_dim,8),
            nn.ReLU(),
            nn.Linear(8,1),
        )

    def forward(self,x):
        return self.network(x)

In [36]:
module=Net(input_dim=X_train.shape[1])

In [37]:
criterion=nn.BCEWithLogitsLoss()
optimizer=torch.optim.SGD(module.parameters(),lr=0.01)

In [43]:

for epoch in range(100):
    outputs = module(X_train)
    loss = criterion(outputs, y_train)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    with torch.no_grad():
        probs = torch.sigmoid(outputs)
        preds = (probs >= 0.5).float()
        acc = (preds == y_train).float().mean()

    print(
        f"Epoch {epoch+1}, "
        f"Loss={loss.item():.4f}, "
        f"Acc={acc.item():.4f}"
    )

Epoch 1, Loss=0.6835, Acc=0.5000
Epoch 2, Loss=0.6833, Acc=0.5000
Epoch 3, Loss=0.6831, Acc=0.5000
Epoch 4, Loss=0.6829, Acc=0.5000
Epoch 5, Loss=0.6827, Acc=0.5000
Epoch 6, Loss=0.6826, Acc=0.5000
Epoch 7, Loss=0.6824, Acc=0.5000
Epoch 8, Loss=0.6822, Acc=0.5000
Epoch 9, Loss=0.6820, Acc=0.5000
Epoch 10, Loss=0.6819, Acc=0.5000
Epoch 11, Loss=0.6817, Acc=0.5000
Epoch 12, Loss=0.6815, Acc=0.5000
Epoch 13, Loss=0.6813, Acc=0.5000
Epoch 14, Loss=0.6812, Acc=0.5000
Epoch 15, Loss=0.6810, Acc=0.5000
Epoch 16, Loss=0.6808, Acc=0.5000
Epoch 17, Loss=0.6807, Acc=0.5000
Epoch 18, Loss=0.6805, Acc=0.5000
Epoch 19, Loss=0.6803, Acc=0.5000
Epoch 20, Loss=0.6801, Acc=0.5000
Epoch 21, Loss=0.6800, Acc=0.5000
Epoch 22, Loss=0.6798, Acc=0.5000
Epoch 23, Loss=0.6796, Acc=0.5000
Epoch 24, Loss=0.6795, Acc=0.5000
Epoch 25, Loss=0.6793, Acc=0.5000
Epoch 26, Loss=0.6791, Acc=0.5000
Epoch 27, Loss=0.6790, Acc=0.5000
Epoch 28, Loss=0.6788, Acc=0.5000
Epoch 29, Loss=0.6786, Acc=0.5000
Epoch 30, Loss=0.6785, Acc=0.5000
Epoch 31, Loss=0.6783, Acc=0.5000
Epoch 32, Loss=0.6781, Acc=0.5000
Epoch 33, Loss=0.6780, Acc=0.5000
Epoch 34, Loss=0.6778, Acc=0.5000
Epoch 35, Loss=0.6777, Acc=0.5000
Epoch 36, Loss=0.6775, Acc=0.5000
Epoch 37, Loss=0.6773, Acc=0.5000
Epoch 38, Loss=0.6772, Acc=0.5000
Epoch 39, Loss=0.6770, Acc=0.5000
Epoch 40, Loss=0.6768, Acc=0.5000
Epoch 41, Loss=0.6767, Acc=0.5000
Epoch 42, Loss=0.6765, Acc=0.5000
Epoch 43, Loss=0.6764, Acc=0.5000
Epoch 44, Loss=0.6762, Acc=0.5000
Epoch 45, Loss=0.6760, Acc=0.5000
Epoch 46, Loss=0.6759, Acc=0.5000
Epoch 47, Loss=0.6757, Acc=0.5000
Epoch 48, Loss=0.6756, Acc=0.5000
Epoch 49, Loss=0.6754, Acc=0.5000
Epoch 50, Loss=0.6753, Acc=0.5000
Epoch 51, Loss=0.6751, Acc=0.5000
Epoch 52, Loss=0.6749, Acc=0.5000
Epoch 53, Loss=0.6748, Acc=0.5000
Epoch 54, Loss=0.6746, Acc=0.5000
Epoch 55, Loss=0.6745, Acc=0.5000
Epoch 56, Loss=0.6743, Acc=0.5000
Epoch 57, Loss=0.6742, Acc=0.5000
Epoch 58, Loss=0.6740, Acc=0.5000
Epoch 59, Loss=0.6738, Acc=0.5000
Epoch 60, Loss=0.6737, Acc=0.5000
Epoch 61, Loss=0.6735, Acc=0.5000
Epoch 62, Loss=0.6734, Acc=0.5000
Epoch 63, Loss=0.6732, Acc=0.5000
Epoch 64, Loss=0.6731, Acc=0.5000
Epoch 65, Loss=0.6729, Acc=0.5000
Epoch 66, Loss=0.6728, Acc=0.5000
Epoch 67, Loss=0.6726, Acc=0.5000
Epoch 68, Loss=0.6725, Acc=0.5000
Epoch 69, Loss=0.6723, Acc=0.5000
Epoch 70, Loss=0.6722, Acc=0.5000
Epoch 71, Loss=0.6720, Acc=0.5000
Epoch 72, Loss=0.6719, Acc=0.5000
Epoch 73, Loss=0.6717, Acc=0.5000
Epoch 74, Loss=0.6716, Acc=0.5000
Epoch 75, Loss=0.6714, Acc=0.5000
Epoch 76, Loss=0.6713, Acc=0.5000
Epoch 77, Loss=0.6711, Acc=0.5000
Epoch 78, Loss=0.6710, Acc=0.5000
Epoch 79, Loss=0.6708, Acc=0.5000
Epoch 80, Loss=0.6707, Acc=0.5000
Epoch 81, Loss=0.6705, Acc=0.5000
Epoch 82, Loss=0.6704, Acc=0.5000
Epoch 83, Loss=0.6702, Acc=0.5000
Epoch 84, Loss=0.6701, Acc=0.5000
Epoch 85, Loss=0.6699, Acc=0.5000
Epoch 86, Loss=0.6698, Acc=0.5000
Epoch 87, Loss=0.6696, Acc=0.5000
Epoch 88, Loss=0.6695, Acc=0.5000
Epoch 89, Loss=0.6693, Acc=0.5000
Epoch 90, Loss=0.6692, Acc=0.5000
Epoch 91, Loss=0.6690, Acc=0.5000
Epoch 92, Loss=0.6689, Acc=0.5000
Epoch 93, Loss=0.6687, Acc=0.5000
Epoch 94, Loss=0.6686, Acc=0.5000
Epoch 95, Loss=0.6684, Acc=0.5000
Epoch 96, Loss=0.6683, Acc=0.5000
Epoch 97, Loss=0.6681, Acc=0.5000
Epoch 98, Loss=0.6680, Acc=0.5000
Epoch 99, Loss=0.6678, Acc=0.5000
Epoch 100, Loss=0.6677, Acc=0.5000